project:
  type: website
  output-dir: _site

website:
  title: "Abdul Bari — Portfolio"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: Projects
        href: projects.qmd
      - text: Blog
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/<your-username>
      - icon: linkedin
        href: https://www.linkedin.com/in/<your-handle>/

format:
  html:
    theme: cosmo
    css: styles.css
