name: Quarto Publish
on:
  push:
    branches: [ main ]      # change to master if your default branch is master
  workflow_dispatch:         # lets you run it manually from Actions

permissions:
  contents: write            # required so the action can push to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      # (Optional) If you use Python in your pages, uncomment below:
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Render site
        run: quarto render

      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
