name: Quarto Publish
on:
  push:
    branches: [ main ]   # change to 'master' if your default branch is master
permissions:
  contents: write        # lets the action push the built site
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render site
        run: quarto render
      - name: Publish to gh-pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
